name: rule files
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *" # 北京时间早晨7点固定更新
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "**/clash-rule/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # 下面的规则是转换为 yaml 格式

      # 仅支持将另类使用了 DOMAIN 或 DOMAIN-SUFFIX 的域名文件转换为behavior: domain
      - name: sed other classical rule
        env:
          NO_SKIP: true
          SED: grep DOMAIN | grep -v "#" | grep -v DOMAIN-KEYWORD | sed 's/DOMAIN,//g' | sed 's/DOMAIN-SUFFIX,/+./g' | sed 's/,/,\x27/g' | sed "s/+/\x27+/g" | sed "s/$/'/" | sed "s/^/  - /" | sed '1ipayload:'
        run: |
          mkdir -p /home/runner/work/clash-yaml/
          curl -sSL https://github.com/privacy-protection-tools/anti-AD/raw/master/anti-ad-surge.txt | ${{ env.SED }} > /home/runner/work/clash-yaml/anti-ad.yaml

      # 仅支持将 使用了通配符 * 的域名文件转换为behavior: domain
      - name: sed * rule
        env:
          NO_SKIP: true
          SED: grep "*." | grep -v "#" | sed 's/\*\./\+\./g' | sed "s/^/'/;s/$/'/" | sed 's/^/  - /' | sed '1ipayload:'
        run: |
          curl -sSL https://github.com/sjhgvr/oisd/raw/main/domainswild_small.txt | ${{ env.SED }} > /home/runner/work/clash-yaml/oisd-small.yaml
          curl -sSL https://github.com/badmojr/1Hosts/raw/master/Lite/wildcards.txt | ${{ env.SED }} > /home/runner/work/clash-yaml/1host-lite.yaml

      # 下面的规则是转换为 text 格式

      # 仅支持将 behavior: classical 转换为behavior: domain format: text
      - name: sed classical rule
        env:
          NO_SKIP: true
          SED: grep DOMAIN | grep -v "#" | grep -v DOMAIN-KEYWORD | sed 's/  - DOMAIN,//g' | sed 's/  - DOMAIN-SUFFIX,/+./g' | sed 's/^/./'
        run: |
          mkdir -p /home/runner/work/clash-text/
          curl -sSL https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Proxy/Proxy_Classical.yaml | ${{ env.SED }} > /home/runner/work/clash-text/proxy.txt
          curl -sSL https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/ChinaMax/ChinaMax_Classical.yaml | ${{ env.SED }} > /home/runner/work/clash-text/china.txt
          curl -sSL https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml | ${{ env.SED }} > /home/runner/work/clash-text/globalmedia.txt

      # 仅支持将另类使用了 DOMAIN 或 DOMAIN-SUFFIX 的域名文件转换为behavior: domain format: text
      - name: sed other classical rule
        env:
          NO_SKIP: true
          SED: grep DOMAIN | grep -v "#" | sed 's/DOMAIN,//g' | sed 's/DOMAIN-SUFFIX,/+./g' | sed 's/^/./'
        run: |
          curl -sSL https://github.com/privacy-protection-tools/anti-AD/raw/master/anti-ad-surge.txt | ${{ env.SED }} > /home/runner/work/clash-text/anti-ad.txt

      # 仅支持将 使用了通配符 * 的域名文件转换为behavior: domain format: text
      - name: sed * rule
        env:
          NO_SKIP: true
          SED: grep "*." | grep -v "#" | sed 's/\*\./\+\./g' | sed 's/^/./'
        run: |
          curl -sSL https://github.com/sjhgvr/oisd/raw/main/domainswild_small.txt | ${{ env.SED }} > /home/runner/work/clash-text/oisd-small.txt
          curl -sSL https://github.com/badmojr/1Hosts/raw/master/Lite/wildcards.txt | ${{ env.SED }} > /home/runner/work/clash-text/1host-lite.txt

      # - name: Upload artifact yaml
      #   uses: actions/upload-artifact@v3.1.2
      #   with:
      #     name: clash-yaml
      #     path: /home/runner/work/clash-yaml/*

      # - name: Checkout repo
      #   uses: actions/checkout@v3.5.2
      
      # - name: Push files to repo
      #   run: |
      #     cd /home/runner/work/clash-yaml
      #     git config --global init.defaultBranch main
      #     git init
      #     git config --global user.name "jklolixxs"
      #     git config --global user.email "bavlzgbq@telegmail.com"
      #     git add -A
      #     git commit -m "Update YAML files"
      #     git push origin HEAD:/refs/heads/clash-rule/clash-yaml/

      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: clash_rule
          deleteOnlyFromDrafts: false

      - name: Release and upload assets
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: clash_rule
          tag_name: clash_rule
          draft: false
          prerelease: false
          files: |
            /home/runner/work/clash-yaml/*
            /home/runner/work/clash-text/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
