name: rule files
on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: sed classical rule
        env:
          NO_SKIP: true
          SED: grep DOMAIN | grep -v DOMAIN-KEYWORD | sed 's/  - DOMAIN,//g' | sed 's/  - DOMAIN-SUFFIX,/+./g'
        run: |
          curl -sSL https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Proxy/Proxy_Classical.yaml | ${{ env.SED }} >> proxy.txt
          curl -sSL https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/ChinaMax/ChinaMax_Classical.yaml | ${{ env.SED }} >> china.txt
          curl -sSL https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml | ${{ env.SED }} >> globalmedia.txt

      - name: sed * rule
        env:
          NO_SKIP: true
          SED: grep "*." | grep -v "#" | sed 's/\*\./\+\./g' | sed '1i\n'
        run: |
          curl -sSL https://github.com/sjhgvr/oisd/raw/main/domainswild_small.txt | ${{ env.SED }} >> oisd-small.txt
          curl -sSL https://github.com/badmojr/1Hosts/raw/master/Lite/wildcards.txt | ${{ env.SED }} >> 1host-lite.txt

      - name: sed payload clash domain rule
        env:
          NO_SKIP: true
          SED: sed 's/payload:/ /g' | sed 's/ - / /g' | sed "s/'/ /g" | sed 's/ //g'
        run: |
          curl -sSL https://github.com/privacy-protection-tools/anti-AD/raw/master/anti-ad-clash.yaml | ${{ env.SED }} >> anit-ad.txt

      - name: Move files to publish directory
        run: |
          mkdir -p clash
          cp *.txt ./clash/

      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: clash_rule
          deleteOnlyFromDrafts: false

      - name: Release and upload assets
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: clash
          tag_name: clash_rule
          draft: false
          prerelease: false
          files: |
            ./clash/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
